projects:
  Portfolio:
    schemaPath: graphql_schema.json
    includes:
      - graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
        region: eu-central-1
        apiId: k7gdhh5o5rbhtihvc464ndtram
        maxDepth: 2
extensions:
  amplify:
    version: 3
