projects:
  Portfolio:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: k7gdhh5o5rbhtihvc464ndtram
        maxDepth: 2
extensions:
  amplify:
    version: 3
