// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MainButton from "../components/MainButton.bs.js";
import * as SharedStyles from "../SharedStyles.bs.js";
import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      gradient: {
        flex: 1
      },
      container: {
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      },
      text: {
        color: "#eee",
        fontSize: 22,
        fontWeight: "500"
      }
    });

function WelcomeScreen(Props) {
  return React.createElement(ReactNative.View, {
              style: SharedStyles.styles.container,
              children: null
            }, React.createElement(ReactNative.Text, {
                  style: SharedStyles.styles.title,
                  children: "Great things here"
                }), React.createElement(MainButton.make, {
                  onPress: (function (param) {
                      
                    }),
                  text: "Hej"
                }));
}

var make = WelcomeScreen;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
