// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Svg from "../assets/Svg.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Spacer from "../components/Spacer.bs.js";
import * as MainButton from "../components/MainButton.bs.js";
import * as RootContext from "../RootContext.bs.js";
import * as SharedStyles from "../SharedStyles.bs.js";
import * as ReactNative from "react-native";

function WelcomeScreen(Props) {
  var match = React.useContext(RootContext.context);
  var setAuthorize = match.setAuthorize;
  return React.createElement(ReactNative.View, {
              style: SharedStyles.styles.container,
              children: null
            }, React.createElement(Spacer.make, {
                  size: /* Size */{
                    _0: /* XXLarge */4
                  }
                }), React.createElement(Spacer.make, {
                  size: /* Size */{
                    _0: /* XXLarge */4
                  }
                }), React.createElement(ReactNative.Text, {
                  style: SharedStyles.styles.title,
                  children: "Great things here"
                }), React.createElement(Spacer.make, {
                  size: /* Size */{
                    _0: /* XXLarge */4
                  }
                }), React.createElement(Spacer.make, {
                  size: /* Size */{
                    _0: /* XXLarge */4
                  }
                }), React.createElement(Spacer.make, {
                  size: /* Size */{
                    _0: /* XXLarge */4
                  }
                }), React.createElement(Svg.$$Blob.make, {}), React.createElement(Spacer.make, {
                  size: /* Auto */0
                }), React.createElement(MainButton.make, {
                  onPress: (function (param) {
                      return Curry._1(setAuthorize, true);
                    }),
                  text: "Log in with Apple ID"
                }), React.createElement(Spacer.make, {
                  size: /* Size */{
                    _0: /* XXLarge */4
                  }
                }));
}

var make = WelcomeScreen;

export {
  make ,
  
}
/* Svg Not a pure module */
