// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SharedStyles from "../SharedStyles.bs.js";
import * as ReactNative from "react-native";
import * as Style$ReactNative from "reason-react-native/src/apis/Style.bs.js";

var styles = ReactNative.StyleSheet.create({
      container: {
        backgroundColor: SharedStyles.colors.main,
        borderRadius: 8,
        alignItems: "center",
        height: 66,
        justifyContent: "center",
        width: Style$ReactNative.pct(100)
      }
    });

function MainButton(Props) {
  var onPress = Props.onPress;
  var text = Props.text;
  return React.createElement(ReactNative.Pressable, {
              children: React.createElement(ReactNative.Text, {
                    style: SharedStyles.styles.subtitle,
                    children: text
                  }),
              onPress: onPress,
              style: styles.container
            });
}

var make = MainButton;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
