// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

var hej = ["hej"];

function Toucher(Props) {
  return React.createElement(ReactNative.View, {
              children: React.createElement(ReactNative.Text, {
                    children: "hej"
                  })
            });
}

var make = Toucher;

export {
  hej ,
  make ,
  
}
/* react Not a pure module */
