// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Root from "./Root.bs.js";
import * as React from "react";
import * as ReactNative from "react-native";
import * as Native from "@react-navigation/native";

function App(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNative.StatusBar, {
                  barStyle: "light-content"
                }), React.createElement(Native.NavigationContainer, {
                  children: React.createElement(Root.Nav.make, {})
                }));
}

var make = App;

export {
  make ,
  
}
/* Root Not a pure module */
