// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as WelcomeScreen from "./WelcomeScreen.bs.js";
import * as Stack$ReactNavigation from "reason-react-navigation/src/Stack.bs.js";
import * as Native from "@react-navigation/native";

var include = Stack$ReactNavigation.Make({});

var $$Screen = include.$$Screen;

var $$Navigator = include.$$Navigator;

function RootNavigation$RootStack(Props) {
  return React.createElement(Native.NavigationContainer, {
              children: React.createElement($$Navigator.make, {
                    headerMode: "none",
                    children: React.createElement($$Screen.make, {
                          name: "unauthorized",
                          component: WelcomeScreen.make
                        })
                  })
            });
}

var RootStack_Navigation = include.Navigation;

var RootStack_HeaderTitle = include.HeaderTitle;

var RootStack_Header = include.Header;

var RootStack_stack = include.stack;

var RootStack_ScreenWithCallback = include.ScreenWithCallback;

var RootStack = {
  Navigation: RootStack_Navigation,
  HeaderTitle: RootStack_HeaderTitle,
  Header: RootStack_Header,
  stack: RootStack_stack,
  ScreenWithCallback: RootStack_ScreenWithCallback,
  $$Screen: $$Screen,
  $$Navigator: $$Navigator,
  make: RootNavigation$RootStack
};

export {
  RootStack ,
  
}
/* include Not a pure module */
