// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";

var spacing = {
  s: 4,
  m: 8,
  l: 16,
  xl: 24,
  xxl: 36
};

var styles = ReactNative.StyleSheet.create({
      container: {
        backgroundColor: "#242533",
        flex: 1,
        paddingHorizontal: spacing.l
      },
      center: {
        alignItems: "center",
        justifyContent: "center"
      },
      title: {
        color: "#FFFFFF",
        fontSize: 32,
        fontWeight: "800"
      },
      subtitle: {
        color: "#FFFFFF",
        fontSize: 24,
        fontWeight: "500"
      },
      body: {
        color: "#FFFFFF",
        fontSize: 14,
        fontWeight: "500"
      }
    });

var colors = {
  main: "#E83B8E",
  secondary: "#F6FF00",
  tertiary: "#7F4DEA",
  bg: "#242533",
  title: "#FFFFFF",
  subtitle: "#FFFFFF",
  body: "#FFFFFF"
};

export {
  colors ,
  spacing ,
  styles ,
  
}
/* styles Not a pure module */
