// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";
import * as ExpoLinearGradient from "expo-linear-gradient";

var styles = ReactNative.StyleSheet.create({
      gradient: {
        flex: 1
      },
      container: {
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      },
      text: {
        color: "#eee",
        fontSize: 22,
        fontWeight: "500"
      }
    });

function WelcomeScreen(Props) {
  return React.createElement(ExpoLinearGradient.LinearGradient, {
              colors: [
                "rgb(50, 13, 47)",
                "rgb(10, 13, 47)"
              ],
              style: styles.gradient,
              start: [
                0.0,
                1.0
              ],
              end: [
                1.0,
                0.0
              ],
              children: null
            }, React.createElement(ReactNative.StatusBar, {
                  barStyle: "light-content"
                }), React.createElement(ReactNative.View, {
                  style: styles.container,
                  children: React.createElement(ReactNative.Text, {
                        style: styles.text,
                        children: "MAGA! " + " 🤖"
                      })
                }));
}

var make = WelcomeScreen;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
